Repository 2quarius/remainder, pull requests merged in 2019-07, with the labels that each got.

#3 complete map and adjust calendar
  trail/app/src/main/AndroidManifest.xml
  trail/app/src/main/java/com/example/trail/Calendar/CalendarFragment.java
  trail/app/src/main/java/com/example/trail/MainActivity.java
  trail/app/src/main/java/com/example/trail/Map/GoogleMapFragment.java
  trail/app/src/main/java/com/example/trail/Map/MapFragment.java
  trail/app/src/main/res/layout/fragment_calendar.xml
  trail/app/src/main/res/layout/fragment_map.xml
Labels: help wanted

#20 messy work
  .travis.yml
  trail/app/build.gradle
  trail/app/src/androidTest/java/com/example/trail/Calendar/CalendarFragmentTest.java
  trail/app/src/androidTest/java/com/example/trail/Lists/SideMenuActivityTest.java
  trail/app/src/androidTest/java/com/example/trail/NewTask/AddTaskActivityTest.java
  trail/app/src/main/java/com/example/trail/Lists/ListsFragment.java
  trail/app/src/main/java/com/example/trail/MainActivity.java
  trail/app/src/main/java/com/example/trail/NewTask/AddTaskActivity.java
  trail/app/src/main/java/com/example/trail/NewTask/SimpleTask/Task.java
Labels: enhancement, help wanted

#22 Account,Information Setting
  trail/app/src/main/java/com/example/trail/Setting/AccountActivity.java
  trail/app/src/main/java/com/example/trail/Setting/InformationActivity.java
  trail/app/src/main/java/com/example/trail/Setting/VoiceActivity.java
  trail/app/src/main/res/drawable/seekbar_custom_drawable.xml
  trail/app/src/main/res/layout/activity_account.xml
  trail/app/src/main/res/layout/activity_information.xml
  trail/app/src/main/res/layout/activity_main.xml
  trail/app/src/main/res/layout/activity_voice.xml
Labels: enhancement

#25 add task manager
  trail/app/build.gradle
  trail/app/src/androidTest/java/com/example/trail/Calendar/CalendarFragmentTest.java
  trail/app/src/androidTest/java/com/example/trail/MainActivityTest.java
  trail/app/src/androidTest/java/com/example/trail/Services/BaiduMapServiceTest.java
  trail/app/src/androidTest/java/com/example/trail/Setting/SettingFragmnetTest.java
  trail/app/src/androidTest/java/com/example/trail/Utility/TaskManagerTest.java
  trail/app/src/main/AndroidManifest.xml
  trail/app/src/main/java/com/example/trail/MainActivity.java
  trail/app/src/main/java/com/example/trail/NewTask/SimpleTask/Task.java
  trail/app/src/main/java/com/example/trail/Services/AlarmManageService.java
  trail/app/src/main/java/com/example/trail/Services/BaiduMapService.java
  trail/app/src/main/java/com/example/trail/Services/RemindReceiver.java
  trail/app/src/main/java/com/example/trail/Utility/DataStorageHelper/StoreRetrieveData.java
  trail/app/src/main/java/com/example/trail/Utility/EnumPack/TabConstants.java
  trail/app/src/main/java/com/example/trail/Utility/EnumPack/TaskConstants.java
  trail/app/src/main/java/com/example/trail/Utility/TaskManager.java
  trail/app/src/main/java/com/example/trail/Utility/UIHelper/CustomTextInputLayout.java
  trail/app/src/main/res/layout/activity_add_task.xml
Labels: enhancement, help wanted

#27 add marker and fix bug
  trail/app/src/main/AndroidManifest.xml
  trail/app/src/main/java/com/example/trail/Calendar/ChineseWeekBar.java
  trail/app/src/main/java/com/example/trail/Lists/ListsFragment.java
  trail/app/src/main/java/com/example/trail/MainActivity.java
  trail/app/src/main/java/com/example/trail/Map/BaiduMapFragment.java
  trail/app/src/main/java/com/example/trail/NewTask/AddTaskActivity.java
  trail/app/src/main/java/com/example/trail/NewTask/SimpleTask/MyLocation.java
  trail/app/src/main/java/com/example/trail/NewTask/SimpleTask/Task.java
  trail/app/src/main/java/com/example/trail/Services/BaiduMapService.java
  trail/app/src/main/res/drawable/add_post_it.png
  trail/app/src/main/res/drawable/place.png
  trail/app/src/main/res/drawable/priority.png
  trail/app/src/main/res/layout/activity_add_task.xml
  trail/app/src/main/res/layout/activity_main.xml
  trail/app/src/main/res/layout/chinese_week_bar.xml
  trail/app/src/main/res/layout/fragment_calendar.xml
  trail/app/src/main/res/mipmap-hdpi/location.png
  trail/app/src/main/res/values/arrays.xml
Labels: enhancement, help wanted

#29 miniTask+TaskCollector+PoiSearch
  trail/app/src/androidTest/java/com/example/trail/NewTask/task/DayTasksTest.java
  trail/app/src/androidTest/java/com/example/trail/NewTask/task/MonthTasksTest.java
  trail/app/src/androidTest/java/com/example/trail/NewTask/task/TaskTest.java
  trail/app/src/main/AndroidManifest.xml
  trail/app/src/main/java/com/example/trail/Lists/ListsFragment.java
  trail/app/src/main/java/com/example/trail/Lists/SideMenuActivity.java
  trail/app/src/main/java/com/example/trail/MainActivity.java
  trail/app/src/main/java/com/example/trail/NewTask/AddTaskActivity.java
  trail/app/src/main/java/com/example/trail/NewTask/Collection/TaskCollector.java
  trail/app/src/main/java/com/example/trail/NewTask/NewTaskActivity.java
  trail/app/src/main/java/com/example/trail/NewTask/SimpleTask/MiniTask.java
  trail/app/src/main/java/com/example/trail/NewTask/SimpleTask/Task.java
  trail/app/src/main/java/com/example/trail/NewTask/task/DayTasks.java
  trail/app/src/main/java/com/example/trail/NewTask/task/MonthTasks.java
  trail/app/src/main/java/com/example/trail/NewTask/task/Task.java
  trail/app/src/main/java/com/example/trail/NewTask/task/Time.java
  trail/app/src/main/java/com/example/trail/Utility/DataStorageHelper/StoreRetrieveData.java
  trail/app/src/main/java/com/example/trail/Utility/EnumPack/TaskConstants.java
  trail/app/src/main/java/com/example/trail/Utility/UIHelper/MyOverlay.java
  trail/app/src/main/java/com/example/trail/overlayutil/BikingRouteOverlay.java
  trail/app/src/main/java/com/example/trail/overlayutil/BusLineOverlay.java
  trail/app/src/main/java/com/example/trail/overlayutil/DrivingRouteOverlay.java
  trail/app/src/main/java/com/example/trail/overlayutil/IndoorPoiOverlay.java
  trail/app/src/main/java/com/example/trail/overlayutil/IndoorRouteOverlay.java
  trail/app/src/main/java/com/example/trail/overlayutil/MassTransitRouteOverlay.java
  trail/app/src/main/java/com/example/trail/overlayutil/OverlayManager.java
  trail/app/src/main/java/com/example/trail/overlayutil/PoiOverlay.java
  trail/app/src/main/java/com/example/trail/overlayutil/TransitRouteOverlay.java
  trail/app/src/main/java/com/example/trail/overlayutil/WalkingRouteOverlay.java
  trail/app/src/main/java/com/example/trail/overlayutil/package.html
  trail/app/src/main/res/drawable/add_post_it.png
  trail/app/src/main/res/drawable/icon_marka.png
  trail/app/src/main/res/drawable/icon_markb.png
  trail/app/src/main/res/drawable/icon_markc.png
  trail/app/src/main/res/drawable/icon_markd.png
  trail/app/src/main/res/drawable/icon_marke.png
  trail/app/src/main/res/drawable/icon_markf.png
  trail/app/src/main/res/drawable/icon_markg.png
  trail/app/src/main/res/drawable/icon_markh.png
  trail/app/src/main/res/drawable/icon_marki.png
  trail/app/src/main/res/drawable/icon_markj.png
  trail/app/src/main/res/drawable/nav_collection.png
  trail/app/src/main/res/drawable/nav_courses.png
  trail/app/src/main/res/drawable/nav_default.png
  trail/app/src/main/res/drawable/nav_new.png
  trail/app/src/main/res/drawable/nav_today.png
  trail/app/src/main/res/layout/activity_add_task.xml
  trail/app/src/main/res/layout/activity_side_menu.xml
  trail/app/src/main/res/layout/dialog.xml
  trail/app/src/main/res/layout/mini_task_add_button.xml
  trail/app/src/main/res/layout/mini_task_checkbox.xml
  trail/app/src/main/res/layout/newtask.xml
  trail/app/src/main/res/menu/drawer.xml
  trail/app/src/main/res/values/strings.xml
Labels: enhancement, help wanted

#31 fix bug
  demo/.gitignore
  demo/.mvn/wrapper/MavenWrapperDownloader.java
  demo/.mvn/wrapper/maven-wrapper.jar
  demo/.mvn/wrapper/maven-wrapper.properties
  demo/mvnw
  demo/mvnw.cmd
  demo/pom.xml
  demo/src/main/.DS_Store
  demo/src/main/java/com/example/demo/DemoApplication.java
  demo/src/main/java/com/example/demo/config/ClientResources.java
  demo/src/main/java/com/example/demo/config/SecurityConfig.java
  demo/src/main/java/com/example/demo/controller/DemoController.java
  demo/src/main/resources/.DS_Store
  demo/src/main/resources/application.yaml
  demo/src/test/java/com/example/demo/DemoApplicationTests.java
  trail/app/src/main/java/com/example/trail/MainActivity.java
Labels: enhancement, help wanted
